#ifndef INFRASTRUCTURE_GLOBAL_H
#define INFRASTRUCTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INFRASTRUCTURE_LIBRARY)
#define INFRASTRUCTURE_EXPORT Q_DECL_EXPORT
#else
#define INFRASTRUCTURE_EXPORT Q_DECL_IMPORT
#endif

#endif // INFRASTRUCTURE_GLOBAL_H
